### ISSUE TITLE
Rename sub-oscillator's "Shuffle" to "Pulsewidth"?

### ISSUE THREAD

**Issue by unfa** [mtytel/helm#131]
From what I see and hear the Sub-oscillator's shuffle is a pulsewidth control. Do you think changing the name could help users understand what it does? I personally like the name "shuffle" but it's mysterious.

**Comment by mtytel** [comment]
It's actually not pulse width, though it's similar.
Instead of changing the length of half the wave form like pulse with this changes the length of every other waveform.
Like this: 0%, 33%, 66%, 100% left to right:
<img width="470" alt="suboscillators" src="https://cloud.githubusercontent.com/assets/311087/25153586/0e87070a-245b-11e7-8ade-ff84449fb99b.png">

**Comment by unfa** [comment]
Aaah - I see.  Thanks for the explanation!
