### ISSUE TITLE
oscillator under the scope doesn't look very clean at all

### ISSUE THREAD

**Issue by quesada** [mtytel/helm#133]
Saw wave has humps. 
So does the square. Huge ones. Like it's doing Phase distortion with a sine. Example captures:
Saw
![screenshot_20170502_222310](https://cloud.githubusercontent.com/assets/182207/25638470/d15a91c4-2f88-11e7-93f1-f0928e1214a6.png)
![screenshot_20170502_223643](https://cloud.githubusercontent.com/assets/182207/25638471/d15b74d6-2f88-11e7-82bd-be36dc9cf613.png)
Square:
![screenshot_20170502_223952](https://cloud.githubusercontent.com/assets/182207/25638472/d3a8c0a4-2f88-11e7-9a85-14d073c094bf.png)

I'm trying to educate my ear on the basic waveforms. I wonder if this will affect my learning if I use Helm?

**Comment by quesada** [comment]
They two oscs are not very stable. A long note show some pulsation, like there was vibrato. The same one on the sub seems to be able to hold the note without such pulsation. Hmm.

**Comment by mtytel** [comment]
The filter in Helm is actually always on. The "flat" filter is actually an all pass filter.
An all pass filter doesn't effect the amplitude of each frequency, but it does effect the phase. 

So here's a learning experience: Waveforms can look totally different but sound exactly the same. 

To illustrate, click and drag on the flat "all pass" filter to change the cutoff and resonance. Every setting (if it's not moving) sounds exactly the same, but if you look at the waveform, it looks totally different at every setting.

Because of this, you may find a spectrum analyzer (like Voxengo SPAN) that measures frequency to be more useful than looking at the oscilloscope.

That said, I should put it in a way to turn the filter off totally. I've been meaning to do that..

**Comment by mtytel** [comment]
Can you elaborate on what is unstable about the oscillators?

**Comment by quesada** [comment]
Tune is slightly not constant. And sound character too. As in it's not the 'boring electricity sound' that you get with a saw on other synths. This may be a good thing.

**Comment by mtytel** [comment]
You're talking about the Tune parameter?
Try turning down one of the oscillators in the mixer. Does it sound more consistent then?

**Comment by mtytel** [comment]
The "all-pass" now doesn't run any filtering so the waveform should look like the original.
Will be out in the next version.
