### ISSUE TITLE
Feature Request: LFO Amplitude Modulation

### ISSUE THREAD

**Issue by zediiiii** [mtytel/helm#145]
Would it be difficult to allow automation of LFO amplitude? This would make some nice sweeping and vibrato effects possible.

**Comment by mtytel** [comment]
The slider to the left of the LFO _should_ do that. Does it not work?

**Comment by zediiiii** [comment]
All of the poly LFO elements work, but none of the mono LFO elements can be automated by the vst gui.. This is true in all three versions of the VST package and the standalone, for both x86 and x64 installers. Specifically, the clicking on a keyboard mod causes automatable parameters to turn green etc, but the mono LFOs do not turn green or behave as other automatable parameters after clicking on a keyboard mod.

I can use my DAW to automate amplitude, frequency, retrigger, sync, tempo, and waveform - so all of the parameters are passing correctly that way.

**Comment by mtytel** [comment]
Oh I see. Yeah that behavior is because you have a poly modulation source and a mono modulation destination. Since you have multiple voice values but only a single destination you have to choose one if the voice values (or average).

This is actually fixed in the version coming out today (or tomorrow). The value sent to a mono modulation destination from a poly source is the value from the last created voice.
