### ISSUE TITLE
JUCE license – IP tracking

### ISSUE THREAD

**Issue by zetamore** [mtytel/helm#203]
I recently red JUCE's license (I have too much free time apparently) – and there are some uncomfortable notions on IP tracking.

> You agree to give notice to the end-users of your Applications that we may
-track the IP addresses associated with their use of the Applications using JUCE

Does helm contain such features ? I reckon there must be an option to opt this out for GPL applications ?

**Comment by mtytel** [comment]
Short answer: No helm doesn't contain the tracking features.

Long answer:
JUCE recently put those tracking features in when they created the "Indie" license. The Indie license is for those who want to create proprietary software, but don't have a budget for the Pro JUCE license to create closed source apps. They give you a free license in exchange for tracking your users.

Since Helm is GPL I get the JUCE GPL license, not the Indie or Pro licenses. So I can enable/disable any features I like as long as I release Helm under the GPL. I disabled the tracking features.

Rant answer:
ROLI enabled the tracking by default though even if you use the GPL version. I didn't like that very much. Then when @falkTX raised concerns about the addition of more user tracking features, a lot of the JUCE community (and developers) jumped on him and labelled him some idealistic radical who was out of touch. Now I really don't like a lot of the JUCE community.

**Comment by zetamore** [comment]
Thanks for the insights!
And great to hear helm is free from tracking.

I bet those conspiracy concerns of JUCE community are surely exaggerated, but it's nice to have freedom to opt such things out in our case.

With tracking on – JUCE probably collects some harmless telemetry data and there is nothing to "jump on" about.

**Comment by mtytel** [comment]
I think you got it in reverse. falkTX didn't like the new tracking data features and rose concerns.
Everyone said it was fine and he was raising concerns for no reason. But the way they did it was pretty distasteful.

No tracking in Helm, so I'm closing the issue.
