### ISSUE TITLE
Helm on M1 mac, Presets don't load nor save

### ISSUE THREAD

**Issue by Beckmeister** [mtytel/helm#295]
Hi,
I just installed Helm on a big sur system (M1, completely new) and when I opened the App (tried all of them, VST, AU and Standalone), I found no presets.
I tried to save a preset, but that didn't work either.
I did a little digging:
The factory presets have been installed in the correct location, but the config file (/Library/Application Support/helm) is missing. not even the folder has been created.
I did look for a config file here on Github. I thought if I could manually put it in the right location, this could fix the problem, but I couldn't find one... I suppose, the config is generated automatically upon installation...
Can anyone help me out with either a working config file, or a hint as to what might have gone wrong?

**Comment by Beckmeister** [comment]
I found a workaround myself... it's a little bit odd, but it seems to work for the factory presets.
I copied the factory presets from the system path to the local path. That's where also a config was created.
The path is ([user]/Library/Application Support/helm) for the config and  ([user]/library/audio/presets/Helm) for the factory presets and also for the uer patches.
Hope this helps someone sometime.
my best.

**Comment by UnlimitydAl** [comment]
My Helm instance has been sitting dormant for about 6 mos due to this no presets issue... I found Beckmeister's workaround yesterday and took a slightly different approach... I copied the config file from my local path to my system path and all the presets showed up as they're supposed to. It seems that the non factory preset folders also need internal folders for bass, arp, lead, foo, etc for those presets to show up... just copying preset files to the respective preset folder was not enough... YMMV

Thank you @Beckmeister !!!!
