### ISSUE TITLE
[feature] Different colors for modulation

### ISSUE THREAD

**Issue by ssj71** [mtytel/helm#4]
I figured I could make an official feature request.

Its impossible to tell what source the modulation is coming from just from the feedback without clicking each source. And even when a source is clicked its a bit difficult to see what has been selected vs what still has no modulation.

Perhaps each source could have a slightly different color just to make this a bit slicker. I realize thats 11 unique colors you'll need to add, but perhaps just different shades of a blue->green gradient would work. I thought about the allowing users to select the shade themselves by scrolling the helm icon next to the modulation source, but I think thats probably overkill.
also when a modulation destination is non-zero a different color (eg. outlined red) would be nice too.

This is just a bit of a nicety. Not really necessary, but please consider it (and feel free to reject it!).

**Comment by mtytel** [comment]
Yea I should somehow make it more obvious where the modulation is coming from. Right now you can right click on a knob to see what sources are attached or right click on the helm modulation buttons to see where the modulation is sent.

The color thing is a bit hard because you can have multiple modulation sources to one knob. You could split up the modulation arc into different colors, but I'm really pushing the GUI performance as it is so I don't think I can do this without totally rewriting the UI in something like OpenGL.

Some other options are when you hover over a knob it makes the modulation sources brighter or something like that. I'll try and come up with some other options.

**Comment by ssj71** [comment]
the mouse over sounds like a good idea. You could do mouseover a destination lights up the connected sources and mouseover a source lights up the connected destinations.

**Comment by mtytel** [comment]
one day i'll get to this

**Comment by mtytel** [comment]
Alright. Finally made something for this.
If you hover over a knob that is modulated, the source button will highlight. Needs a little prettying up, but it's functional.
