### ISSUE TITLE
feature request: some documentation

### ISSUE THREAD

**Issue by magnetophon** [mtytel/helm#46]
Most of Helm is wonderfully self explanatory, but three things in particular have me puzzled:

-What do the "H" buttons in the oscillator section do?
-What is Shuffle, in the sub section?
-What do the transpose and tune knobs in the feedback section do?

**Comment by mtytel** [comment]
Yea I'm going to release some docs when the 1.0 release comes out.

Here's some rough answer to your questions though. Really there should be some pictures:
"H" stands for harmonize. If it's disabled, you get standard detuned oscillators close the the same frequency. If harmonize is enabled, The first voice plays at the note frequency, the second voices plays 2x the note frequency, the third voice plays 3x the note frequency, etc.
It's basically a way to change the timbre. I've been thinking about changing it into a slider or x/y pad instead of a button that changes the multiplier of each harmonic. It would allow some cool timbre changing modulation I think.

Shuffle alternates between short and long waveforms of the sub oscillator. It's pretty similar to pulse width of a square wave but instead of changing the length of the first half and second half of the waveform, it change the length of two adjacent waveforms.
Example - if Shuffle is at 50%, the sub oscillator will alternate between a wave that's 1/2 the length and a wave that's 3/2 the length.

The feedback section is a delay line (comb filter) that's in harmony with current note being played. That way you can emphasize or diminish certain harmonics. The transpose and tune knobs change the harmonization of this delay line. So if you're playing a 400Hz note, and you set the feedback transpose to -12 semitones, the delay line will have a frequency of 200Hz.

I'll include this all (better written) in some better documentation down the line. Let me know if you have any more questions!

**Comment by magnetophon** [comment]
Thanks, all clear.
For now, you might wanna copy the above to the readme.

**Comment by unfa** [comment]
I've got one more question!

What is the Cross Modulation between the two oscillators exactly doing? What type of modulation is it? How it's affecting the sound of both oscillators? Is it just the second one modulating the first one or they are both modulating each other?

**Comment by mtytel** [comment]
First go at a manual is here:
http://tytel.org/static/docs/helm_manual.pdf

If it's missing anything let me know!
