### ISSUE TITLE
Make controls more precise

### ISSUE THREAD

**Issue by suhr** [mtytel/helm#68]
Controls are too sensitive to set them accurately. Make control more accurate when Ctrl is held (+ more accurate scroll).

**Comment by mtytel** [comment]
I think this already works. Though it might be alt or shift instead of ctrl..

**Comment by suhr** [comment]
Wait, ctrl + mouse works, but it sometimes jumps over values, this is not very helpful.
Ctrl + scroll does not work.

**Comment by rghvdberg** [comment]
Ctrl + scroll would be handy :+1:

**Comment by mtytel** [comment]
I made all the discretized knobs (the transpose knobs, pitch bend range) less sensitive to mouse movements in 0.6.1. Let me know if you want any more knobs' precisions changed.
Thinking about the ctrl+scroll, might be a bug for the JUCE framework because I'm using their UI library to handle all that.
