### ISSUE TITLE
Windows 10 Patches Folder not same location as patch files -> no patches visible

### ISSUE THREAD

**Issue by stutzjr** [mtytel/helm#73]
Just downloaded Helm v.0.6.0 (windows 32 bit) msi binary for my Windows 10 system.
I did not choose standard folders for either the program or the VST install:
"D:\Program Files\Helm"
"D:\Document Sync\VST Plugins"
When I load Helm, no patches are visible, but I know they are in the folder:
"D:\Program Files\Helm\Patches"
When I try to save a dummy patch inside Helm, it is saved to the following folder:
"C:\Users\Richard\AppData\Roaming\Helm\patches\User Patches"

In Windows 10-
Should I have to manually copy the contents of each subfolder
from the "\Helm\Patches" folder to the "\Users\...\User Patches" folder?

Can I not instruct Helm to look in a specific folder?
Can it not be expected to look in it's own installation folder?

**Comment by mtytel** [comment]
Sorry it took me so long to get to this.
Problem was I wanted to have a common place for the the standalone and plugin to share patches.
Windows registry is a mystery to me so I just put it in Program Files\Helm\Patches.

Now there's a common location to story the factory install patches here:
C:\Users\Public\Documents\Helm\Patches
And when you save patches they'll all go to either your Documents folder in "Helm\Patches" or into your My Documents folder under "Helm\Patches"
I believe My Documents for Windows 7 and earlier and Documents for 8 and later.

So this'll be fixed in the next (0.7) release.
